### ISSUE TITLE
Iris fails to process reasonably good pics

### ISSUE THREAD

**Issue by sha2007** [critichu/Iris#2]
Please see the log. IRIS didn't live up to its expectations claimed by the paper. Greatly appreciate helpful suggestions to make iris process these image files.

![emm2](https://cloud.githubusercontent.com/assets/7814894/23860295/710a942e-07fe-11e7-9e64-adfb2bc78411.JPG)
![emm2 jpg grid](https://cloud.githubusercontent.com/assets/7814894/23860317/7c4807b8-07fe-11e7-8dbe-ea31aff21680.jpg)

[iris_v0.9.7.5_2017.03.08_08.08.26.log.txt](https://github.com/critichu/Iris/files/838604/iris_v0.9.7.5_2017.03.08_08.08.26.log.txt)

**Comment by critichu** [comment]
It works just fine if you crop it yourself, see example and result:
![sha2007 picture1 crop](https://cloud.githubusercontent.com/assets/9034429/23861212/ae8dce96-0809-11e7-8d67-63df408cdad8.jpg)

![sha2007 picture1 crop jpg grid](https://cloud.githubusercontent.com/assets/9034429/23861242/bfabfb94-0809-11e7-975c-7ef583188c41.jpg)


To tell Iris you've already cropped the image yourself, please set the following parameter in the _iris.user.settings.json_ file:
`"UserCroppedImage": true`


Here's a _iris.user.settings.json_ with this setting already activated for the _"Colony growth"_ profile:
[iris.user.settings.json.zip](https://github.com/critichu/Iris/files/838669/iris.user.settings.json.zip)

**Comment by sha2007** [comment]
Thanks.
Sha

**Comment by sha2007** [comment]
Cropping helps in one and doesn't in another. The program randomly picks which image to process
[iris_v0.9.7.5_2017.03.13_04.36.02.log.txt](https://github.com/critichu/Iris/files/838926/iris_v0.9.7.5_2017.03.13_04.36.02.log.txt)
![emm1 copy jpg grid 16 35 35](https://cloud.githubusercontent.com/assets/7814894/23864920/f00a293a-080b-11e7-8076-3406f8d9f88f.jpg)

**Comment by sha2007** [comment]
The original file
![emm1](https://cloud.githubusercontent.com/assets/7814894/23865002/20cba29c-080c-11e7-9932-e1f2b84661b9.JPG)

**Comment by critichu** [comment]
When cropping, please leave more space for the top row.
Can you please explain what you mean by "the program randomly picks which image to process"?

**Comment by sha2007** [comment]
I tried around 5 different pics and only 2 were successfully processed.

**Comment by critichu** [comment]
please try to give enough space around the colonies, see example result picture below:

![sha2007 picture2 crop2 png grid](https://cloud.githubusercontent.com/assets/9034429/23875357/70cf563a-0839-11e7-9ca5-9a7522235342.jpg)
